### PR TITLE
Correct pixel format and fix checkpatch warnings

### PR DESCRIPTION
**Pull request by linkunfa**

### CODE REVIEW

**Comment by avifishman** [comment]
Hi Joseph,

Just lately we decided that VCD + ECE area will be at 0x33400000 and the size will be 20MB (actually it was 24MB also in prev version):
Now I see that it was changed to 0x33000000 and the size will be 24MB.
- reg = <0x0 0x33400000 0x0 0x01800000>;
+ reg = <0x0 0x33000000 0x0 0x01800000>;

Can we make it
- reg = <0x0 0x33400000 0x0 0x01400000>;

Since it is inside linux area it doesn't heart the upper mapping but if we can save linux why not?

Thanks,
Avi

**Comment by avifishman** [comment]
+Marvin

From: IS20 Avi Fishman ***@***.***>
Sent: Sunday, November 6, 2022 11:46 PM
To: Nuvoton-Israel/linux ***@***.***>; Nuvoton-Israel/linux ***@***.***>; CS20 KWLiu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [Nuvoton-Israel/linux] Correct pixel format and fix checkpatch warnings (PR #162)

Hi Joseph,

Just lately we decided that VCD + ECE area will be at 0x33400000 and the size will be 20MB (actually it was 24MB also in prev version):
Now I see that it was changed to 0x33000000 and the size will be 24MB.
- reg = <0x0 0x33400000 0x0 0x01800000>;
+ reg = <0x0 0x33000000 0x0 0x01800000>;

Can we make it
- reg = <0x0 0x33400000 0x0 0x01400000>;

Since it is inside linux area it doesn't heart the upper mapping but if we can save linux why not?

Thanks,
Avi

**Comment by linkunfa** [comment]
Hi Avi,

The necessary memory for KVM feature is around 21M:
- V4L2 video buffers: 5M * 3
- VCD frame buffer: 5M
- Used by V4L2 framework: ~1M

And the CMA memory has a limitation of 4MB alignment, so we have to set the size to 24MB.

The memory area could be at 0x33400000 but it would cause u-boot printing “ERROR: reserving fdt memory region failed (addr=33400000 size=1800000)”. So we moved the area to 0x33000000 even though this error won't impact any functionality.

BTW, the "reserved video-memory" even can be removed from device tree. In this case, it will use kernel default CMA (the area is controlled by kernel and the size is controlled by CONFIG_CMA_SIZE_MBYTES=32 in default) and hence we are unable to set the CMA area as "non-ECC region" in advance to improve the KVM performance when ECC is enabled.

Marvin

**Comment by avifishman** [comment]
OK, as long as the VCD + ECE area will not exceed 0x34800000, and that is the case now. So it is OK.

Thanks,
Avi

**Pull request merged**
